# Generated by Django 3.1.7 on 2021-04-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_social'),
        ('users', '0002_applylist_created_at'),
    ]

    operations = [
    ]
