# Generated by Django 3.1.7 on 2021-05-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20210430_1802'),
        ('users', '0003_merge_20210430_1720'),
    ]

    operations = [
    ]
