# Generated by Django 3.1.7 on 2021-05-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210503_2029'),
        ('users', '0004_merge_20210503_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification',
            field=models.ManyToManyField(related_name='userapply', through='users.ApplyList', to='companies.Notification'),
        ),
    ]
