# Generated by Django 3.1.7 on 2021-04-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_auto_20210428_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='period',
            new_name='end_working',
        ),
        migrations.AddField(
            model_name='career',
            name='start_working',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
