# Generated by Django 3.1.7 on 2021-04-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_auto_20210428_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='end_working',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='career',
            name='start_working',
            field=models.CharField(max_length=50),
        ),
    ]
